ALERT_EVIDENCE = {
    "Stats": {
        "ExecutionTime": 0.0156691,
        "resource_usage": {
            "cache": {
                "memory": {"hits": 0, "misses": 0, "total": 0},
                "disk": {"hits": 0, "misses": 0, "total": 0},
            },
            "cpu": {"user": "00:00:00", "kernel": "00:00:00", "total cpu": "00:00:00"},
            "memory": {"peak_per_node": 64915008},
        },
        "dataset_statistics": [{"table_row_count": 2, "table_size": 2760}],
    },
    "Schema": [
        {"Name": "Timestamp", "Type": "DateTime"},
        {"Name": "AlertId", "Type": "String"},
        {"Name": "Title", "Type": "String"},
        {"Name": "Categories", "Type": "String"},
        {"Name": "AttackTechniques", "Type": "String"},
        {"Name": "ServiceSource", "Type": "String"},
        {"Name": "DetectionSource", "Type": "String"},
        {"Name": "EntityType", "Type": "String"},
        {"Name": "EvidenceRole", "Type": "String"},
        {"Name": "EvidenceDirection", "Type": "String"},
        {"Name": "FileName", "Type": "String"},
        {"Name": "FolderPath", "Type": "String"},
        {"Name": "SHA1", "Type": "String"},
        {"Name": "SHA256", "Type": "String"},
        {"Name": "FileSize", "Type": "Int64"},
        {"Name": "ThreatFamily", "Type": "String"},
        {"Name": "RemoteIP", "Type": "String"},
        {"Name": "RemoteUrl", "Type": "String"},
        {"Name": "AccountName", "Type": "String"},
        {"Name": "AccountDomain", "Type": "String"},
        {"Name": "AccountSid", "Type": "String"},
        {"Name": "AccountObjectId", "Type": "String"},
        {"Name": "AccountUpn", "Type": "String"},
        {"Name": "DeviceId", "Type": "String"},
        {"Name": "DeviceName", "Type": "String"},
        {"Name": "LocalIP", "Type": "String"},
        {"Name": "NetworkMessageId", "Type": "String"},
        {"Name": "EmailSubject", "Type": "String"},
        {"Name": "Application", "Type": "String"},
        {"Name": "ApplicationId", "Type": "Int32"},
        {"Name": "OAuthApplicationId", "Type": "String"},
        {"Name": "ProcessCommandLine", "Type": "String"},
        {"Name": "RegistryKey", "Type": "String"},
        {"Name": "RegistryValueName", "Type": "String"},
        {"Name": "RegistryValueData", "Type": "String"},
        {"Name": "AdditionalFields", "Type": "String"},
        {"Name": "Severity", "Type": "String"},
        {"Name": "CloudResource", "Type": "String"},
        {"Name": "CloudPlatform", "Type": "String"},
        {"Name": "ResourceType", "Type": "String"},
        {"Name": "ResourceID", "Type": "String"},
        {"Name": "SubscriptionId", "Type": "String"},
    ],
    "Results": [
        {
            "Timestamp": "2023-12-14T15:05:37Z",
            "AlertId": "fa8fca28f0-d2fe-0958-fc00-08dbfcb62ea6",
            "Title": "Email reported by user as malware or phish",
            "Categories": '["InitialAccess"]',
            "AttackTechniques": '["Phishing (T1566)"]',
            "ServiceSource": "Microsoft Defender for Office 365",
            "DetectionSource": "Microsoft Defender for Office 365",
            "EntityType": "Mailbox",
            "EvidenceRole": "Impacted",
            "EvidenceDirection": "",
            "FileName": "",
            "FolderPath": "",
            "SHA1": "",
            "SHA256": "",
            "FileSize": None,
            "ThreatFamily": "",
            "RemoteIP": "",
            "RemoteUrl": "",
            "AccountName": "mhlazuno",
            "AccountDomain": "",
            "AccountSid": "S-1-12-1-2456824860-1209112221-3954467253-1440763578",
            "AccountObjectId": "92702c1c-969d-4811-b561-b4ebba4ee055",
            "AccountUpn": "mhlazuno@securitydemo.net",
            "DeviceId": "",
            "DeviceName": "",
            "LocalIP": "",
            "NetworkMessageId": "",
            "EmailSubject": "",
            "Application": "",
            "ApplicationId": None,
            "OAuthApplicationId": "",
            "ProcessCommandLine": "",
            "RegistryKey": "",
            "RegistryValueName": "",
            "RegistryValueData": "",
            "AdditionalFields": '{"$id":"1","MailboxPrimaryAddress":"mhlazuno@securitydemo.net","DisplayName":"Mykyta Hlazunov","Upn":"mhlazuno@securitydemo.net","AadId":"92702c1c-969d-4811-b561-b4ebba4ee055","RiskLevel":"None","EntitySources":["Alert"],"Type":"mailbox","UserSid":"S-1-12-1-2456824860-1209112221-3954467253-1440763578","AccountName":"mhlazuno","Role":0,"MergeByKey":"1qa3FivFSzW4HAsMbZ1AAwXbQcE=","MergeByKeyHex":"D6A6B7162BC54B35B81C0B0C6D9D400305DB41C1"}',
            "Severity": "Low",
            "CloudResource": "",
            "CloudPlatform": "",
            "ResourceType": "",
            "ResourceID": "",
            "SubscriptionId": "",
        },
        {
            "Timestamp": "2023-12-14T15:05:37Z",
            "AlertId": "fa8fca28f0-d2fe-0958-fc00-08dbfcb62ea6",
            "Title": "Email reported by user as malware or phish",
            "Categories": '["InitialAccess"]',
            "AttackTechniques": '["Phishing (T1566)"]',
            "ServiceSource": "Microsoft Defender for Office 365",
            "DetectionSource": "Microsoft Defender for Office 365",
            "EntityType": "MailMessage",
            "EvidenceRole": "Related",
            "EvidenceDirection": "",
            "FileName": "",
            "FolderPath": "",
            "SHA1": "",
            "SHA256": "",
            "FileSize": None,
            "ThreatFamily": "",
            "RemoteIP": "",
            "RemoteUrl": "",
            "AccountName": "",
            "AccountDomain": "",
            "AccountSid": "",
            "AccountObjectId": "",
            "AccountUpn": "",
            "DeviceId": "",
            "DeviceName": "",
            "LocalIP": "",
            "NetworkMessageId": "b8a1305a-3260-44f7-aca4-08dbfcadd4b6",
            "EmailSubject": "Test url from endpoint",
            "Application": "",
            "ApplicationId": None,
            "OAuthApplicationId": "",
            "ProcessCommandLine": "",
            "RegistryKey": "",
            "RegistryValueName": "",
            "RegistryValueData": "",
            "AdditionalFields": '{"$id":"1","Recipient":"mhlazuno@securitydemo.net","Sender":"\\"Oksana Lisovska -X (olisovsk - SOFTSERVE INC at Cisco)\\" <olisovsk@cisco.com>","SenderIP":"216.71.137.209","P2Sender":"\\"Oksana Lisovska -X (olisovsk - SOFTSERVE INC at Cisco)\\" <olisovsk@cisco.com>","ReceivedDate":"2023-12-14T14:06:13Z","NetworkMessageId":"b8a1305a-3260-44f7-aca4-08dbfcadd4b6","Subject":"Test url from endpoint","StartTimeUtc":"2023-12-14T15:05:37Z","EndTimeUtc":"2023-12-14T15:05:37Z","EntitySources":["Alert"],"Type":"mailMessage","Urn":None,"Source":"OATP","FirstSeen":"0001-01-01T00:00:00","SourceEntityType":"User","SourceEntityId":"mhlazuno@securitydemo.net","SourceExtendedProperties":"KesMailId:15086703987392738;FingerprintData:DBD21A8C.56426AEC.B9FE6C8C.51371CF4.2000C;SubmissionCategory:Email;RescanVerdict:Spam;SubmissionSource:Microsoft;SubmissionId:85c2f1fb-e3ba-4663-a43d-08dbfcb60aa9;OriginalVerdict:Spam","Role":1,"AttachmentCount":0,"UrlCount":0,"MergeByKey":"z0xnyMWhVxNux+IcKvw2o0UgU94=","MergeByKeyHex":"CF4C67C8C5A157136EC7E21C2AFC36A3452053DE"}',
            "Severity": "Low",
            "CloudResource": "",
            "CloudPlatform": "",
            "ResourceType": "",
            "ResourceID": "",
            "SubscriptionId": "",
        },
    ],
}
